import { bookingSources, bookingStatuses, zoneStatuses } from "../../booking/statuses";

export const bookingsTable = {
  name: "bookings",
  columns: {
    id: { type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
    reference: { type: "text", nullable: false, unique: true },
    customerId: { name: "customer_id", type: "uuid", references: "customers.id", nullable: false },
    status: { type: "text", nullable: false, enumValues: bookingStatuses },
    source: { type: "text", nullable: false, default: "public_booking", enumValues: bookingSources },
    packageId: { name: "package_id", type: "text", references: "services.id", nullable: false },
    requestedStartAt: { name: "requested_start_at", type: "timestamptz", nullable: true },
    serviceEndsAt: { name: "service_ends_at", type: "timestamptz", nullable: true },
    blockedUntil: { name: "blocked_until", type: "timestamptz", nullable: true },
    serviceDurationMinutes: { name: "service_duration_minutes", type: "integer", nullable: false, default: 0 },
    travelBufferMinutes: { name: "travel_buffer_minutes", type: "integer", nullable: false, default: 45 },
    estimatedTotalMinor: { name: "estimated_total_minor", type: "integer", nullable: false, default: 0 },
    finalTotalMinor: { name: "final_total_minor", type: "integer", nullable: true },
    depositDueMinor: { name: "deposit_due_minor", type: "integer", nullable: false, default: 0 },
    depositPaidMinor: { name: "deposit_paid_minor", type: "integer", nullable: false, default: 0 },
    balanceDueMinor: { name: "balance_due_minor", type: "integer", nullable: false, default: 0 },
    balancePaidMinor: { name: "balance_paid_minor", type: "integer", nullable: false, default: 0 },
    currency: { type: "text", nullable: false, default: "GBP" },
    fullAddress: { name: "full_address", type: "text", nullable: false },
    postcode: { type: "text", nullable: false },
    normalizedPostcode: { name: "normalized_postcode", type: "text", nullable: false },
    zoneStatus: { name: "zone_status", type: "text", nullable: false, enumValues: zoneStatuses },
    vehicleCount: { name: "vehicle_count", type: "integer", nullable: false, default: 1 },
    parkingAvailable: { name: "parking_available", type: "text", nullable: true },
    accessToWaterAvailable: { name: "access_to_water_available", type: "boolean", nullable: false, default: false },
    accessToElectricityAvailable: { name: "access_to_electricity_available", type: "boolean", nullable: false, default: false },
    accessibleParkingLocation: { name: "accessible_parking_location", type: "boolean", nullable: false, default: false },
    parkingNotes: { name: "parking_notes", type: "text", nullable: true },
    accessNotes: { name: "access_notes", type: "text", nullable: true },
    extraNotes: { name: "extra_notes", type: "text", nullable: true },
    marketingPhotoConsent: { name: "marketing_photo_consent", type: "boolean", nullable: false, default: false },
    priceAdjustmentReason: { name: "price_adjustment_reason", type: "text", nullable: true },
    adminNotes: { name: "admin_notes", type: "text", nullable: true },
    createdAt: { name: "created_at", type: "timestamptz", nullable: false, default: "now()" },
    updatedAt: { name: "updated_at", type: "timestamptz", nullable: false, default: "now()" },
    approvedAt: { name: "approved_at", type: "timestamptz", nullable: true },
    declinedAt: { name: "declined_at", type: "timestamptz", nullable: true },
  },
  indexes: [
    { name: "bookings_reference_idx", columns: ["reference"], unique: true },
    { name: "bookings_status_idx", columns: ["status"] },
    { name: "bookings_requested_start_at_idx", columns: ["requested_start_at"] },
    { name: "bookings_blocked_until_idx", columns: ["blocked_until"] },
    { name: "bookings_normalized_postcode_idx", columns: ["normalized_postcode"] },
    { name: "bookings_customer_id_idx", columns: ["customer_id"] },
  ],
  checks: [
    "service_duration_minutes >= 0",
    "travel_buffer_minutes >= 0",
    "estimated_total_minor >= 0",
    "deposit_due_minor >= 0",
    "deposit_paid_minor >= 0",
    "balance_due_minor >= 0",
    "balance_paid_minor >= 0",
    "vehicle_count >= 1",
    "currency = 'GBP'",
  ],
  futureConstraints: [
    "Prevent overlapping blocking statuses with transaction locks and a PostgreSQL range/exclusion constraint.",
  ],
} as const;
